### ISSUE TITLE
Reading Dot annotations

### ISSUE THREAD

**Issue by akshitac8** [erikalu/class-agnostic-counting#2]
Hey @erikalu 
I am unable to understand the line
```
lb = np.asarray(lb[:, :, 0] > 230)
```
I believe that this takes all the values greater than 230 in the red channel. However, dot annotations are a binary mask of shape ((Height, Width)).

It would be great if you could explain the use case for this line.

Thanks,
Akshita Gupta

**Comment by WeidiXie** [comment]
have you checked the dot annotation map ? how do you know it's binary mask ?

**Comment by erikalu** [comment]
Hi @akshitac8 you are correct, this line of code was for a specific dataset where the labels were in this form (red channel). You can modify it to suit your needs.

**Comment by akshitac8** [comment]
Thank you @erikalu :)
