### ISSUE TITLE
test mode

### ISSUE THREAD

**Issue by MNCTTY** [erikalu/class-agnostic-counting#3]
Hi!
Do you have some code to test pretrained model?

**Comment by erikalu** [comment]
Hi, we are not currently working on releasing that code but to describe it at a high level: if counting by density estimation, you would sum the predicted maps and normalize by the scaling factor used in training (100 for the pretrained model). If counting by detection, you would find the local maximums (e.g. using skimage's peak_local_max).

**Comment by sri9s** [comment]
@erikalu , the predicted output is of shape 1x200x200. How is this to be visualised?

**Comment by erikalu** [comment]
> @erikalu , the predicted output is of shape 1x200x200. How is this to be visualised?

You can normalize the values to be in the correct range and then visualize it as a grayscale 200x200 image.
