### ISSUE TITLE
Can I get some kind of docker ???

### ISSUE THREAD

**Issue by Nhatcao99** [erikalu/class-agnostic-counting#6]
Hi, I am trying to run your code but its dependencies seems a bit too old. I try to install here and there with anaconda but it is either not available and the alternatives seem don't like each other a lot. So can I have some form of docker make this easy? I 'd love to try out your work.
Thank you very much.

**Comment by erikalu** [comment]
Hi @Nhatcao99 I'll see if I can get to this soon and let you know.

**Comment by Nhatcao99** [comment]
Thank you very much!

**Comment by erikalu** [comment]
I updated the code and added a conda environment that you can try.
I also added a demo script. Hope that helps!

**Comment by Nhatcao99** [comment]
Thank you for the change! I truly appreciate the new changes. They helps a lot.
